all:
	64tass -o test_text.prg test_text.asm
	64tass -o test_pointer.prg test_pointer.asm
	64tass -o test_petscii.prg test_petscii.asm
	64tass -o test_labels.prg test_labels.asm

clean:
	rm -f test_text.prg test_pointer.prg test_petscii.prg test_labels.prg
