name = "PetsciiShifted"
description = "PETSCII shifted (text mode) character set."

[variants]
"0" = "RAW_00"
"1" = "RAW_01"
"2" = "RAW_02"
"3" = "KEY_RUN_STOP"
"4" = "RAW_04"
"5" = "COLOR_WHITE"
"6" = "RAW_06"
"7" = "RAW_07"
"8" = "SHIFT_DISABLE"
"9" = "SHIFT_ENABLE"
"10" = "RAW_0A"
"11" = "RAW_0B"
"12" = "RAW_0C"
"13" = "KEY_RETURN"
"14" = "LOWER_CASE"
"15" = "RAW_0F"
"16" = "RAW_10"
"17" = "KEY_CRSR_DOWN"
"18" = "REVERSE_ON"
"19" = "KEY_HOME"
"20" = "KEY_DELETE"
"21" = "RAW_15"
"22" = "RAW_16"
"23" = "RAW_17"
"24" = "RAW_18"
"25" = "RAW_19"
"26" = "RAW_1A"
"27" = "RAW_1B"
"28" = "COLOR_RED"
"29" = "KEY_CRSR_RIGHT"
"30" = "COLOR_GREEN"
"31" = "COLOR_BLUE"
"32" = "KEY_SPACE"
"33" = "KEY_EXCLAMATION"
"34" = "KEY_QUOTE"
"35" = "KEY_HASH"
"36" = "KEY_DOLLAR"
"37" = "KEY_PERCENT"
"38" = "KEY_AMPERSAND"
"39" = "KEY_APOSTROPHE"
"40" = "KEY_PAREN_LEFT"
"41" = "KEY_PAREN_RIGHT"
"42" = "KEY_ASTERISK"
"43" = "KEY_PLUS"
"44" = "KEY_COMMA"
"45" = "KEY_MINUS"
"46" = "KEY_PERIOD"
"47" = "KEY_SLASH"
"48" = "KEY_0"
"49" = "KEY_1"
"50" = "KEY_2"
"51" = "KEY_3"
"52" = "KEY_4"
"53" = "KEY_5"
"54" = "KEY_6"
"55" = "KEY_7"
"56" = "KEY_8"
"57" = "KEY_9"
"58" = "KEY_COLON"
"59" = "KEY_SEMICOLON"
"60" = "KEY_LESS_THAN"
"61" = "KEY_EQUAL"
"62" = "KEY_GREATER_THAN"
"63" = "KEY_QUESTION"
"64" = "KEY_AT"
"65" = "KEY_a"
"66" = "KEY_b"
"67" = "KEY_c"
"68" = "KEY_d"
"69" = "KEY_e"
"70" = "KEY_f"
"71" = "KEY_g"
"72" = "KEY_h"
"73" = "KEY_i"
"74" = "KEY_j"
"75" = "KEY_k"
"76" = "KEY_l"
"77" = "KEY_m"
"78" = "KEY_n"
"79" = "KEY_o"
"80" = "KEY_p"
"81" = "KEY_q"
"82" = "KEY_r"
"83" = "KEY_s"
"84" = "KEY_t"
"85" = "KEY_u"
"86" = "KEY_v"
"87" = "KEY_w"
"88" = "KEY_x"
"89" = "KEY_y"
"90" = "KEY_z"
"91" = "KEY_BRACKET_LEFT"
"92" = "KEY_POUND"
"93" = "KEY_BRACKET_RIGHT"
"94" = "KEY_ARROW_UP"
"95" = "KEY_ARROW_LEFT"
"96" = "SHIFT_ASTERISK"
"97" = "KEY_A"
"98" = "KEY_B"
"99" = "KEY_C"
"100" = "KEY_D"
"101" = "KEY_E"
"102" = "KEY_F"
"103" = "KEY_G"
"104" = "KEY_H"
"105" = "KEY_I"
"106" = "KEY_J"
"107" = "KEY_K"
"108" = "KEY_L"
"109" = "KEY_M"
"110" = "KEY_N"
"111" = "KEY_O"
"112" = "KEY_P"
"113" = "KEY_Q"
"114" = "KEY_R"
"115" = "KEY_S"
"116" = "KEY_T"
"117" = "KEY_U"
"118" = "KEY_V"
"119" = "KEY_W"
"120" = "KEY_X"
"121" = "KEY_Y"
"122" = "KEY_Z"
"123" = "SHIFT_PLUS"
"124" = "CBM_ASTERISK"
"125" = "SHIFT_MINUS"
"126" = "SHIFT_ARROW_UP"
"127" = "CBM_MINUS"
"128" = "RAW_80"
"129" = "COLOR_ORANGE"
"130" = "RAW_82"
"131" = "RAW_83"
"132" = "RAW_84"
"133" = "KEY_F1"
"134" = "KEY_F3"
"135" = "KEY_F5"
"136" = "KEY_F7"
"137" = "KEY_F2"
"138" = "KEY_F4"
"139" = "KEY_F6"
"140" = "KEY_F8"
"141" = "SHIFT_RETURN"
"142" = "RAW_8E"
"143" = "RAW_8F"
"144" = "COLOR_BLACK"
"145" = "KEY_CRSR_UP"
"146" = "REVERSE_OFF"
"147" = "KEY_CLEAR"
"148" = "KEY_INSERT"
"149" = "COLOR_BROWN"
"150" = "COLOR_LIGHT_RED"
"151" = "COLOR_DARK_GRAY"
"152" = "COLOR_GRAY"
"153" = "COLOR_LIGHT_GREEN"
"154" = "COLOR_LIGHT_BLUE"
"155" = "COLOR_LIGHT_GRAY"
"156" = "COLOR_PURPLE"
"157" = "KEY_CRSR_LEFT"
"158" = "COLOR_YELLOW"
"159" = "COLOR_CYAN"
"160" = "SHIFT_SPACE"
"161" = "CBM_K"
"162" = "CBM_I"
"163" = "CBM_T"
"164" = "CBM_AT"
"165" = "CBM_G"
"166" = "CBM_PLUS"
"167" = "CBM_M"
"168" = "CBM_V"
"169" = "SHIFT_POUND"
"170" = "CBM_MINUS"
"171" = "CBM_Q"
"172" = "CBM_D"
"173" = "CBM_Z"
"174" = "CBM_S"
"175" = "CBM_P"
"176" = "CBM_A"
"177" = "CBM_E"
"178" = "CBM_R"
"179" = "CBM_W"
"180" = "CBM_H"
"181" = "CBM_J"
"182" = "CBM_L"
"183" = "CBM_Y"
"184" = "CBM_U"
"185" = "CBM_O"
"186" = "SHIFT_AT"
"187" = "CBM_F"
"188" = "CBM_C"
"189" = "CBM_X"
"190" = "CBM_B"
"191" = "CBM_N"
"192" = "ALT_SHIFT_ASTERISK"
"193" = "ALT_KEY_A"
"194" = "ALT_KEY_B"
"195" = "ALT_KEY_C"
"196" = "ALT_KEY_D"
"197" = "ALT_KEY_E"
"198" = "ALT_KEY_F"
"199" = "ALT_KEY_G"
"200" = "ALT_KEY_H"
"201" = "ALT_KEY_I"
"202" = "ALT_KEY_J"
"203" = "ALT_KEY_K"
"204" = "ALT_KEY_L"
"205" = "ALT_KEY_M"
"206" = "ALT_KEY_N"
"207" = "ALT_KEY_O"
"208" = "ALT_KEY_P"
"209" = "ALT_KEY_Q"
"210" = "ALT_KEY_R"
"211" = "ALT_KEY_S"
"212" = "ALT_KEY_T"
"213" = "ALT_KEY_U"
"214" = "ALT_KEY_V"
"215" = "ALT_KEY_W"
"216" = "ALT_KEY_X"
"217" = "ALT_KEY_Y"
"218" = "ALT_KEY_Z"
"219" = "ALT_SHIFT_PLUS"
"220" = "ALT_CBM_ASTERISK"
"221" = "ALT_SHIFT_MINUS"
"222" = "ALT_SHIFT_ARROW_UP"
"223" = "ALT_CBM_MINUS"
"224" = "ALT_SHIFT_SPACE"
"225" = "ALT_CBM_K"
"226" = "ALT_CBM_I"
"227" = "ALT_CBM_T"
"228" = "ALT_CBM_AT"
"229" = "ALT_CBM_G"
"230" = "ALT_CBM_PLUS"
"231" = "ALT_CBM_M"
"232" = "ALT_CBM_V"
"233" = "ALT_SHIFT_POUND"
"234" = "ALT_CBM_MINUS"
"235" = "ALT_CBM_Q"
"236" = "ALT_CBM_D"
"237" = "ALT_CBM_Z"
"238" = "ALT_CBM_S"
"239" = "ALT_CBM_P"
"240" = "ALT_CBM_A"
"241" = "ALT_CBM_E"
"242" = "ALT_CBM_R"
"243" = "ALT_CBM_W"
"244" = "ALT_CBM_H"
"245" = "ALT_CBM_J"
"246" = "ALT_CBM_L"
"247" = "ALT_CBM_Y"
"248" = "ALT_CBM_U"
"249" = "ALT_CBM_O"
"250" = "ALT_SHIFT_AT"
"251" = "ALT_CBM_F"
"252" = "ALT_CBM_C"
"253" = "ALT_CBM_X"
"254" = "ALT_CBM_B"
"255" = "ALT_CBM_N"
