name = "VicColors"
description = "Color constants for the Commodore VIC-20 (VIC) video chip."

[variants]
"0" = "BLACK"
"1" = "WHITE"
"2" = "RED"
"3" = "CYAN"
"4" = "PURPLE"
"5" = "GREEN"
"6" = "BLUE"
"7" = "YELLOW"
"8" = "ORANGE"
"9" = "LIGHT_ORANGE"
"10" = "PINK"
"11" = "LIGHT_CYAN"
"12" = "LIGHT_PURPLE"
"13" = "LIGHT_GREEN"
"14" = "LIGHT_BLUE"
"15" = "LIGHT_YELLOW"
