use crate::disassembler::LABEL_COLUMN_WIDTH;
use crate::state::AppState;
use std::path::PathBuf;

// CSS class name abbreviations used throughout this file:
//   ad = address          by = bytes           mn = mnemonic
//   op = operand          cm = comment         lb = label
//   il = inline-label     cc = code-cell       ml = mid-label
//   mld = mid-label-def   sr = separator-row   bh = block-header
//   as = assignment

const HTML_START: &str = r#"<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Regenerator 2000 Disassembly</title>
<style>
:root {
  --bg-color: #ffffff;
  --text-color: #24292f;
  --address-color: #57606a;
  --bytes-color: #6e7781;
  --mnemonic-color: #cf222e;
  --operand-color: #0550ae;
  --comment-color: #6e7781;
  --label-color: #953800;
  --link-color: #0969da;
  --mid-label-color: #8250df;
  --highlight-bg: rgba(84, 174, 255, 0.3);
  --highlight-border: #0969da;
}
[data-theme="dark"] {
  --bg-color: #0d1117;
  --text-color: #c9d1d9;
  --address-color: #8b949e;
  --bytes-color: #6e7681;
  --mnemonic-color: #ff7b72;
  --operand-color: #79c0ff;
  --comment-color: #8b949e;
  --label-color: #ffa657;
  --link-color: #58a6ff;
  --mid-label-color: #d2a8ff;
  --highlight-bg: rgba(56, 139, 253, 0.15);
  --highlight-border: #1f6feb;
}
body { font-family: ui-monospace, SFMono-Regular, 'SF Pro Mono', Menlo, Consolas, 'Liberation Mono', monospace; font-size: 12px; line-height: 1.45; background-color: var(--bg-color); color: var(--text-color); margin: 0; padding: 20px; }
table { border-collapse: collapse; width: 100%; max-width: 1200px; margin: 0 auto; }
td { padding: 0px 8px; line-height: 1.4; vertical-align: top; white-space: pre; }
a { color: var(--link-color); text-decoration: none; }
a:hover { text-decoration: underline; }
.ad { color: var(--address-color); text-align: left; }
.ad a { color: inherit; }
.by { color: var(--bytes-color); text-align: left; }
.mn { color: var(--mnemonic-color); text-align: left; }
.op { color: var(--operand-color); text-align: left; }
.cm { color: var(--comment-color); }
.lb { color: var(--label-color); font-weight: bold; }
.ml { color: var(--mid-label-color); }
.sr { height: 15px; }
.cc { display: flex; align-items: top; padding: 0 !important; }
.cc .il { width: 20ch; flex-shrink: 0; color: var(--label-color); font-weight: bold; }
.cc .mn { min-width: 6ch; flex-shrink: 0; }
.cc > .mn:first-child { padding-left: 20ch; }
.cc .op { min-width: 15ch; flex-shrink: 0; padding-left: 1ch; }
.cc .cm { padding: 0 8px; margin-left: 4ch; }
.cc.as { padding: 0 8px !important; }
.cc.as .lb { min-width: 42ch; flex-shrink: 0; }
.cc.bh .cm { margin-left: 0ch; padding: 0; }
.mld { display: inline-block; min-width: 60ch; }
tr:target td { background-color: var(--highlight-bg); }
tr:target td:first-child { border-left: 3px solid var(--highlight-border); }
#theme-toggle { position: fixed; top: 20px; right: 20px; padding: 8px 16px; background-color: var(--text-color); color: var(--bg-color); border: 1px solid var(--text-color); cursor: pointer; font-family: inherit; font-weight: bold; }
</style>
</head>
<body>
<button id="theme-toggle">Toggle Theme</button>
<table>
"#;

/// Exports the disassembly to an HTML file.
///
/// # Errors
/// Returns an error if the file cannot be written.
pub fn export_html(state: &AppState, path: &PathBuf) -> std::io::Result<()> {
    let formatter = state.get_formatter();
    let mut output = String::new();

    output.push_str(HTML_START);

    // Header block
    let source_name = state
        .file_path
        .as_ref()
        .and_then(|p| p.file_name())
        .and_then(|n| n.to_str())
        .unwrap_or("unknown");
    let base_name = path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("export");
    let comment = formatter.comment_prefix();
    let separator = format!(
        "{comment}=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
    );
    let version_line = format!(
        "{comment} Auto-generated by Regenerator 2000 v{}",
        env!("CARGO_PKG_VERSION")
    );
    // Build the static part of the header (lines that are always present)
    let static_header_lines = [
        separator.as_str(),
        comment,
        &version_line,
        &format!(
            "{comment} <a href=\"https://github.com/ricardoquesada/regenerator2000\">https://github.com/ricardoquesada/regenerator2000</a>"
        ),
        comment,
        &format!("{comment} Exported from: {source_name}"),
        comment,
    ];
    for header_line in &static_header_lines {
        output.push_str(&format!(
            "<tr><td colspan=\"5\" class=\"cm\">{}</td></tr>\n",
            header_line
        ));
    }
    // Assembler-specific instructions (e.g. "Assemble with: 64tass ...")
    let formatter_header =
        formatter.format_file_header(base_name, state.settings.use_illegal_opcodes);
    if !formatter_header.is_empty() {
        // The first line is always "{prefix} Assemble with:" — turn the assembler
        // name into a hyperlink pointing to its homepage.
        let linked_header = format!(
            "{comment} Assemble with <a href=\"{}\">{}</a>:",
            formatter.homepage_url(),
            formatter.name()
        );
        output.push_str(&format!(
            "<tr><td colspan=\"5\" class=\"cm\">{}</td></tr>\n",
            linked_header
        ));
        // Remaining lines (the actual command, blank separator, etc.)
        for line in formatter_header.lines().skip(1) {
            let escaped = line
                .replace('&', "&amp;")
                .replace('<', "&lt;")
                .replace('>', "&gt;");
            output.push_str(&format!(
                "<tr><td colspan=\"5\" class=\"cm\">{}</td></tr>\n",
                escaped
            ));
        }
    } else {
        // Fallback for formatters without specific build instructions
        let fallback = format!(
            "{comment} <a href=\"{}\">{}</a> assembly format.",
            formatter.homepage_url(),
            formatter.name()
        );
        output.push_str(&format!(
            "<tr><td colspan=\"5\" class=\"cm\">{}</td></tr>\n",
            fallback
        ));
    }
    output.push_str(&format!(
        "<tr><td colspan=\"5\" class=\"cm\">{}</td></tr>\n",
        separator
    ));
    output.push_str("<tr class=\"sr\"><td colspan=\"5\"></td></tr>\n");

    let ctx = crate::disassembler::context::DisassemblyContext {
        data: &state.raw_data,
        block_types: &state.block_types,
        labels: &state.labels,
        origin: state.origin,
        settings: &state.settings,
        system_comments: &state.system_comments,
        user_side_comments: &state.user_side_comments,
        user_line_comments: &state.user_line_comments,
        immediate_value_formats: &state.immediate_value_formats,
        cross_refs: &state.cross_refs,
        collapsed_blocks: &[], // Always uncollapse for export
        splitters: &state.splitters,
        scopes: &state.scopes,
    };
    let full_disassembly = state.disassembler.disassemble_ctx(&ctx);
    let external_lines = state.get_external_label_definitions(true);

    let mut label_name_to_addr = std::collections::HashMap::new();
    for (addr, label_vec) in &state.labels {
        for l in label_vec {
            label_name_to_addr.insert(l.name.clone(), *addr);
        }
    }

    let all_lines: Vec<&crate::disassembler::DisassemblyLine> = external_lines
        .iter()
        .chain(full_disassembly.iter())
        .collect();

    let mut formatted_rows = Vec::new();
    for line in &all_lines {
        let mut row_str = String::new();
        // Special case: Empty line (separator)
        if line.mnemonic.is_empty() && line.bytes.is_empty() && line.comment.is_empty() {
            row_str.push_str("<tr class=\"sr\"><td colspan=\"5\"></td></tr>\n");
            formatted_rows.push(row_str);
            continue;
        }

        // Special case: Splitter (internal only)
        if line.mnemonic == "{splitter}" {
            formatted_rows.push(row_str);
            continue;
        }

        // Special case: Pure comment line (e.g. legend/header from external label
        // definitions). These have no bytes and their mnemonic is already a full
        // comment string starting with the comment prefix.  Render them as a
        // block-header comment row so they don't get misclassified as assignments
        // (the mnemonic may contain '=' as part of "zpf_ = Zero Page Field").
        if line.bytes.is_empty() && line.mnemonic.starts_with(formatter.comment_prefix()) {
            let escaped = line
                .mnemonic
                .replace('&', "&amp;")
                .replace('<', "&lt;")
                .replace('>', "&gt;");
            row_str.push_str(&format!(
                "<tr><td colspan=\"2\"></td><td colspan=\"3\" class=\"cc bh\"><span class=\"cm\">{escaped}</span></td></tr>\n"
            ));
            formatted_rows.push(row_str);
            continue;
        }

        // 1. Mid-instruction labels
        if line.bytes.len() > 1 {
            for j in 1..line.bytes.len() {
                let mid_addr = line.address.wrapping_add(j as u16);
                if let Some(label_vec) = state.labels.get(&mid_addr)
                    && let Some(label) =
                        crate::disassembler::resolve_label(label_vec, mid_addr.0, &state.settings)
                {
                    let mut name = label.name.clone();
                    if label.label_type == crate::state::LabelType::LocalUserDefined
                        && let Some(p) = formatter.local_label_prefix()
                        && !name.starts_with(p)
                    {
                        name = format!("{}{}", p, name);
                    }
                    let label_def = format!("{} =*+${:02x}", name, j);

                    // Build x-ref comment with hyperlinks for this mid-address
                    let mid_comment = if let Some(refs) = state.cross_refs.get(&mid_addr)
                        && !refs.is_empty()
                        && state.settings.max_xref_count > 0
                    {
                        let origin_val = state.origin.0;
                        let size = state.raw_data.len() as u16;
                        let mut all_refs = refs.clone();
                        all_refs.sort_unstable();
                        all_refs.dedup();
                        let max = state.settings.max_xref_count;
                        let suffix = if all_refs.len() > max { ", ..." } else { "" };
                        let refs_str: Vec<String> = all_refs
                            .iter()
                            .take(max)
                            .map(|r| {
                                if r.0 >= origin_val && r.0 < origin_val + size {
                                    format!("<a href=\"#L{:04X}\">${:04X}</a>", r.0, r.0)
                                } else {
                                    format!("${:04X}", r.0)
                                }
                            })
                            .collect();
                        format!(
                            "<span class=\"cm\"> {} x-ref: {}{}</span>",
                            formatter.comment_prefix(),
                            refs_str.join(", "),
                            suffix
                        )
                    } else {
                        String::new()
                    };

                    row_str.push_str(&format!("<tr id=\"L{:04X}\"><td colspan=\"2\"></td><td colspan=\"3\" class=\"cc ml\"><span class=\"mld\">{}</span>{}</td></tr>\n", mid_addr.0, label_def, mid_comment));
                }
            }
        }

        // 2. User line comments
        if let Some(comment) = &line.line_comment {
            for comment_line in comment.lines() {
                row_str.push_str(&format!(
                    "<tr><td colspan=\"2\"></td><td colspan=\"3\" class=\"cc bh\"><span class=\"cm\">{} {}</span></td></tr>\n",
                    formatter.comment_prefix(),
                    comment_line
                ));
            }
        }

        // 3. Labels on top or inline
        let label_text = if let Some(label) = &line.label {
            formatter.format_label_definition(label)
        } else {
            String::new()
        };

        let mut inline_label_html = String::new();
        if !label_text.is_empty() {
            let label_on_own_line = label_text.len() > LABEL_COLUMN_WIDTH;
            if label_on_own_line {
                row_str.push_str(&format!(
                    "<tr><td colspan=\"2\"></td><td colspan=\"3\" class=\"cc lb\">{}</td></tr>\n",
                    label_text
                ));
            } else {
                inline_label_html = format!("<span class=\"il\">{}</span>", label_text);
            }
        }

        // When no inline label, omit the span entirely. CSS rule
        // `.cc > .mn:first-child { padding-left: 20ch }` handles alignment.

        // 4. Address part
        let address_td = if !line.bytes.is_empty() || line.label.is_some() {
            format!(
                "<td class=\"ad\"><a href=\"#L{:04X}\">${:04X}</a></td>",
                line.address.0, line.address.0
            )
        } else {
            "<td></td>".to_string()
        };

        // 5. Bytes part
        let bytes_td = if line.show_bytes {
            let bytes_formatted = line
                .bytes
                .iter()
                .map(|b| format!("{:02x}", b))
                .collect::<Vec<_>>()
                .join(" ");
            format!("<td class=\"by\">{}</td>", bytes_formatted)
        } else {
            "<td></td>".to_string()
        };

        // 6. Instruction part
        let mut operand_str = line.operand.clone();
        if let Some(target) = line.target_address {
            let origin_val = state.origin.0;
            let size = state.raw_data.len() as u16;
            if target.0 >= origin_val && target.0 < origin_val + size {
                operand_str = format!("<a href=\"#L{:04X}\">{}</a>", target.0, line.operand);
            }
        } else {
            let mut new_op = String::new();
            let mut current_word = String::new();
            for c in line.operand.chars() {
                if c.is_alphanumeric() || c == '_' {
                    current_word.push(c);
                } else {
                    if !current_word.is_empty() {
                        if let Some(addr) = label_name_to_addr.get(&current_word) {
                            new_op.push_str(&format!(
                                "<a href=\"#L{:04X}\">{}</a>",
                                addr.0, current_word
                            ));
                        } else {
                            new_op.push_str(&current_word);
                        }
                        current_word.clear();
                    }
                    new_op.push(c);
                }
            }
            if !current_word.is_empty() {
                if let Some(addr) = label_name_to_addr.get(&current_word) {
                    new_op.push_str(&format!(
                        "<a href=\"#L{:04X}\">{}</a>",
                        addr.0, current_word
                    ));
                } else {
                    new_op.push_str(&current_word);
                }
            }
            operand_str = new_op;
        }
        // 6. Instruction part
        let is_assignment = line.mnemonic.contains('=');

        // 7. Comment part
        let mut comment_str = line.comment.clone();
        // Format x-refs in comments as hyperlinks if they are internal
        if comment_str.contains("x-ref:") {
            let origin_val = state.origin.0;
            let size = state.raw_data.len() as u16;
            let words: Vec<String> = comment_str
                .split(' ')
                .map(|w| {
                    if w.starts_with('$') {
                        let hex_str = w.trim_matches(|c| c == '$' || c == ',' || c == ';');
                        if let Ok(addr) = u16::from_str_radix(hex_str, 16)
                            && addr >= origin_val
                            && addr < origin_val + size
                        {
                            return format!("<a href=\"#L{:04X}\">${:04X}</a>", addr, addr)
                                + if w.ends_with(',') { "," } else { "" };
                        }
                    }
                    w.to_string()
                })
                .collect();
            comment_str = words.join(" ");
        }

        let comment_part = if comment_str.is_empty() {
            String::new()
        } else {
            format!(
                "<span class=\"cm\">{} {}</span>",
                formatter.comment_prefix(),
                comment_str
            )
        };

        if is_assignment {
            let addr_val = line.external_label_address.unwrap_or(line.address).0;
            row_str.push_str(&format!(
                "<tr id=\"L{:04X}\"><td colspan=\"2\"></td><td colspan=\"3\" class=\"cc as\"><span class=\"lb\">{} {}</span>{}</td></tr>\n",
                addr_val, line.mnemonic, operand_str, comment_part
            ));
        } else {
            let tr_id = if !line.bytes.is_empty() || line.label.is_some() {
                format!(" id=\"L{:04X}\"", line.address.0)
            } else {
                String::new()
            };
            row_str.push_str(&format!(
                "<tr{}>{}{}<td colspan=\"3\" class=\"cc\">{}<span class=\"mn\">{}</span><span class=\"op\">{}</span>{}</td></tr>\n",
                tr_id, address_td, bytes_td, inline_label_html, line.mnemonic, operand_str, comment_part
            ));
        }
        formatted_rows.push(row_str);
    }
    let mut i = 0;
    while i < all_lines.len() {
        let line = all_lines[i];
        // External-label definition lines carry the label's address in `line.address`
        // which may coincidentally fall inside an ExternalFile block.  They must
        // never be treated as ExternalFile content — they are just equate definitions.
        let is_ext_label_def = line.external_label_address.is_some() && line.bytes.is_empty();
        let offset = line.address.0 as isize - state.origin.0 as isize;
        let is_external = !is_ext_label_def
            && offset >= 0
            && (offset as usize) < state.block_types.len()
            && state.block_types[offset as usize] == crate::state::BlockType::ExternalFile;

        if is_external {
            let start_idx = i;
            let mut end_idx = i;
            while end_idx < all_lines.len() {
                let next_line = all_lines[end_idx];
                let next_offset = next_line.address.0 as isize - state.origin.0 as isize;
                let next_external = if next_offset >= 0
                    && (next_offset as usize) < state.block_types.len()
                {
                    state.block_types[next_offset as usize] == crate::state::BlockType::ExternalFile
                } else {
                    false
                };
                if !next_external {
                    break;
                }
                end_idx += 1;
            }

            let mut external_rows = String::new();
            for row in formatted_rows.iter().take(end_idx).skip(start_idx) {
                external_rows.push_str(row);
            }

            let base_name = path
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("export");
            let start_addr = all_lines[start_idx].address;
            let ext_filename = format!("{base_name}_{start_addr:04x}.html");
            let ext_path = path
                .parent()
                .unwrap_or(&std::path::PathBuf::from("."))
                .join(&ext_filename);

            let mut ext_output = String::new();
            ext_output.push_str(HTML_START);
            ext_output.push_str(&external_rows);
            ext_output.push_str(HTML_END);
            let _ = std::fs::write(&ext_path, ext_output);

            let (mnemonic, operand) = formatter.format_binary_include(&ext_filename);
            let linked_operand = operand.replace(
                &ext_filename,
                &format!("<a href=\"{}\">{}</a>", ext_filename, ext_filename),
            );
            let link_row = format!(
                "<tr><td class=\"ad\">${:04X}</td><td></td><td colspan=\"3\" class=\"cc\"><span class=\"mn\">{}</span><span class=\"op\">{}</span></td></tr>\n",
                start_addr.0, mnemonic, linked_operand
            );
            output.push_str(&link_row);

            i = end_idx;
        } else {
            output.push_str(&formatted_rows[i]);
            i += 1;
        }
    }

    const HTML_END: &str = r#"</table>
<script>
const toggleBtn = document.getElementById('theme-toggle');
const urlParams = new URLSearchParams(window.location.search);
let currentTheme = urlParams.get('theme') || 'dark';

function updateLinks() {
  document.querySelectorAll('a').forEach(link => {
    let href = link.getAttribute('href');
    if (href && !href.startsWith('#')) {
      let parts = href.split('?');
      let base = parts[0];
      let params = new URLSearchParams(parts[1] || '');
      params.set('theme', currentTheme);
      link.setAttribute('href', base + '?' + params.toString());
    }
  });
}

document.documentElement.setAttribute('data-theme', currentTheme);
toggleBtn.textContent = currentTheme === 'dark' ? 'Light Mode' : 'Dark Mode';
updateLinks();

toggleBtn.addEventListener('click', () => {
  currentTheme = currentTheme === 'dark' ? 'light' : 'dark';
  document.documentElement.setAttribute('data-theme', currentTheme);
  toggleBtn.textContent = currentTheme === 'dark' ? 'Light Mode' : 'Dark Mode';
  updateLinks();

  const newUrl = new URL(window.location.href);
  newUrl.searchParams.set('theme', currentTheme);
  window.history.pushState({}, '', newUrl);
});
</script>
</body>
</html>
"#;

    output.push_str(HTML_END);
    std::fs::write(path, output)
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_export_html() {
        let mut state = AppState::new();
        state.origin = crate::state::Addr(0x1000);
        state.raw_data = vec![0xA9, 0x00, 0x8D, 0x20, 0xD0, 0x60];
        state.block_types = vec![crate::state::BlockType::Code; 6];

        state.labels.insert(
            crate::state::Addr(0x1000),
            vec![crate::state::Label {
                name: "Start".to_string(),
                kind: crate::state::LabelKind::User,
                label_type: crate::state::LabelType::UserDefined,
            }],
        );

        let path = PathBuf::from("test_output.html");
        let _ = std::fs::remove_file(&path);

        let res = export_html(&state, &path);
        assert!(res.is_ok());

        let content = std::fs::read_to_string(&path).unwrap();

        assert!(content.contains("<!DOCTYPE html>"));
        assert!(content.contains("<table>"));
        assert!(content.contains("</table>"));

        assert!(content.contains("id=\"L1000\""));
        assert!(content.contains("id=\"L1002\""));

        assert!(content.contains("a9 00"));
        assert!(content.contains("8d 20 d0"));

        assert!(content.contains("class=\"mn\""));
        assert!(content.contains("class=\"op\""));

        let _ = std::fs::remove_file(&path);
    }

    /// Regression test: line comments must align with the label column.
    ///
    /// The code-cell for a line comment must:
    /// - Use the `bh` (block-header) class (which has `margin-left: 0; padding: 0`)
    /// - NOT contain an `il` (inline-label) span (which would push content to the
    ///   mnemonic column)
    /// This ensures line comments start at the same column as labels.
    #[test]
    fn test_line_comment_aligns_with_label_column() {
        let mut state = AppState::new();
        state.origin = crate::state::Addr(0x1000);
        state.raw_data = vec![0xA9, 0x00, 0x60];
        state.block_types = vec![crate::state::BlockType::Code; 3];

        state.labels.insert(
            crate::state::Addr(0x1000),
            vec![crate::state::Label {
                name: "my_routine".to_string(),
                kind: crate::state::LabelKind::User,
                label_type: crate::state::LabelType::UserDefined,
            }],
        );
        state
            .user_line_comments
            .insert(crate::state::Addr(0x1000), "Load accumulator".to_string());

        let path = PathBuf::from("test_line_comment_align.html");
        let _ = std::fs::remove_file(&path);

        let res = export_html(&state, &path);
        assert!(res.is_ok());

        let content = std::fs::read_to_string(&path).unwrap();

        // Line comment row must use bh (block-header) class for label-column alignment.
        assert!(
            content.contains("class=\"cc bh\""),
            "Line comment must use bh class for label-column alignment"
        );

        // Line comment must NOT contain an il (inline-label) span, which would shift it right.
        for line in content.lines() {
            if line.contains("cc bh") {
                assert!(
                    !line.contains("class=\"il\""),
                    "Line comment row must not contain il span (would misalign): {line}"
                );
            }
        }

        // The il span must appear in regular instruction rows (sanity check
        // that labels are rendered in code-cells with inline-label).
        assert!(
            content.contains("<span class=\"il\">my_routine</span>"),
            "Inline labels must use the il span"
        );

        let _ = std::fs::remove_file(&path);
    }

    /// Regression test: line comments must have a space between the comment prefix and text.
    ///
    /// Correct:   `; Load accumulator`
    /// Bug was:   `;Load accumulator`
    #[test]
    fn test_line_comment_has_space_after_prefix() {
        let mut state = AppState::new();
        state.origin = crate::state::Addr(0x2000);
        state.raw_data = vec![0x60];
        state.block_types = vec![crate::state::BlockType::Code; 1];

        state
            .user_line_comments
            .insert(crate::state::Addr(0x2000), "Return to caller".to_string());

        let path = PathBuf::from("test_line_comment_space.html");
        let _ = std::fs::remove_file(&path);

        let res = export_html(&state, &path);
        assert!(res.is_ok());

        let content = std::fs::read_to_string(&path).unwrap();

        // Must have "; Return" (with space), not ";Return"
        assert!(
            content.contains("; Return to caller"),
            "Line comment must have a space between ';' and the comment text"
        );
        assert!(
            !content.contains(";Return"),
            "Line comment must not have ';' directly adjacent to the comment text"
        );

        let _ = std::fs::remove_file(&path);
    }

    /// Regression test: side comments (on instruction lines) must have a space after the prefix.
    ///
    /// Correct:   `; Save value`
    /// Bug would be:  `;Save value`
    #[test]
    fn test_side_comment_has_space_after_prefix() {
        let mut state = AppState::new();
        state.origin = crate::state::Addr(0x3000);
        state.raw_data = vec![0x8D, 0x00, 0xD0];
        state.block_types = vec![crate::state::BlockType::Code; 3];

        state
            .user_side_comments
            .insert(crate::state::Addr(0x3000), "Store to VIC".to_string());

        let path = PathBuf::from("test_side_comment_space.html");
        let _ = std::fs::remove_file(&path);

        let res = export_html(&state, &path);
        assert!(res.is_ok());

        let content = std::fs::read_to_string(&path).unwrap();

        // Side comment must have "; Store" (with space)
        assert!(
            content.contains("; Store to VIC"),
            "Side comment must have a space between ';' and the comment text"
        );

        let _ = std::fs::remove_file(&path);
    }

    /// Regression test: the CSS must include `padding: 0` for block-header comments.
    ///
    /// Without this, block-header comments inherit `padding: 0 8px` from
    /// `.cc .cm`, causing a ~1ch horizontal offset vs labels.
    #[test]
    fn test_css_block_header_has_zero_padding() {
        let mut state = AppState::new();
        state.origin = crate::state::Addr(0x4000);
        state.raw_data = vec![0x60];
        state.block_types = vec![crate::state::BlockType::Code; 1];

        let path = PathBuf::from("test_css_padding.html");
        let _ = std::fs::remove_file(&path);

        let res = export_html(&state, &path);
        assert!(res.is_ok());

        let content = std::fs::read_to_string(&path).unwrap();

        // The block-header comment rule must zero out padding to prevent
        // inheriting the 8px left-padding from `.cc .cm`.
        assert!(
            content.contains(".cc.bh .cm { margin-left: 0ch; padding: 0; }"),
            "CSS must include padding: 0 for block-header comments to align with labels"
        );

        let _ = std::fs::remove_file(&path);
    }

    /// Regression test: multi-line comments must each be on their own row,
    /// all aligned at the label column.
    #[test]
    fn test_multiline_comment_alignment() {
        let mut state = AppState::new();
        state.origin = crate::state::Addr(0x5000);
        state.raw_data = vec![0xA9, 0x00, 0x60];
        state.block_types = vec![crate::state::BlockType::Code; 3];

        state.user_line_comments.insert(
            crate::state::Addr(0x5000),
            "First line\nSecond line\nThird line".to_string(),
        );

        let path = PathBuf::from("test_multiline_comment.html");
        let _ = std::fs::remove_file(&path);

        let res = export_html(&state, &path);
        assert!(res.is_ok());

        let content = std::fs::read_to_string(&path).unwrap();

        // Each line of a multi-line comment must be in its own bh (block-header) row
        let block_header_count = content.matches("cc bh").count();
        assert!(
            block_header_count >= 3,
            "Expected at least 3 block-header rows for 3 comment lines, got {block_header_count}"
        );

        // Each line must have proper spacing
        assert!(content.contains("; First line"));
        assert!(content.contains("; Second line"));
        assert!(content.contains("; Third line"));

        // No block-header row should contain an il (inline-label) span
        for line in content.lines() {
            if line.contains("cc bh") {
                assert!(
                    !line.contains("class=\"il\""),
                    "Multi-line comment row must not contain il span: {line}"
                );
            }
        }

        let _ = std::fs::remove_file(&path);
    }

    /// Regression test: instruction rows without labels must NOT emit an empty
    /// inline-label span. The CSS rule `.cc > .mn:first-child` handles the
    /// 20ch indent automatically.
    #[test]
    fn test_no_empty_inline_label_span() {
        let mut state = AppState::new();
        state.origin = crate::state::Addr(0x6000);
        state.raw_data = vec![0xA9, 0x00, 0x60]; // LDA #$00 ; RTS
        state.block_types = vec![crate::state::BlockType::Code; 3];

        // No labels — all rows should omit the inline-label span
        let path = PathBuf::from("test_no_empty_il.html");
        let _ = std::fs::remove_file(&path);

        let res = export_html(&state, &path);
        assert!(res.is_ok());

        let content = std::fs::read_to_string(&path).unwrap();

        // The CSS rule for first-child mnemonic must exist
        assert!(
            content.contains(".cc > .mn:first-child { padding-left: 20ch; }"),
            "CSS must have .cc > .mn:first-child rule for label-less alignment"
        );

        // No instruction row should contain an empty il span
        assert!(
            !content.contains("<span class=\"il\"></span>"),
            "Empty il spans must not be emitted; CSS :first-child handles alignment"
        );

        let _ = std::fs::remove_file(&path);
    }
}
