use crate::state::AppState;
use std::path::PathBuf;

const HTML_START: &str = r#"<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Regenerator 2000 Disassembly</title>
<style>
:root {
  --bg-color: #ffffff;
  --text-color: #000000;
  --address-color: #098658;
  --bytes-color: #001080;
  --mnemonic-color: #0000ff;
  --operand-color: #a31515;
  --comment-color: #008000;
  --label-color: #795e26;
  --link-color: #005fb8;
  --mid-label-color: #af00db;
}
[data-theme="dark"] {
  --bg-color: #1e1e1e;
  --text-color: #d4d4d4;
  --address-color: #9cdcfe;
  --bytes-color: #b5cea8;
  --mnemonic-color: #569cd6;
  --operand-color: #ce9178;
  --comment-color: #6a9955;
  --label-color: #dcdcaa;
  --link-color: #4ec9b0;
  --mid-label-color: #c586c0;
}
body { font-family: 'Courier New', Courier, monospace; background-color: var(--bg-color); color: var(--text-color); margin: 0; padding: 20px; }
table { border-collapse: collapse; width: 100%; max-width: 1200px; margin: 0 auto; }
td { padding: 0px 8px; line-height: 1.4; vertical-align: top; white-space: nowrap; }
a { color: var(--link-color); text-decoration: none; }
a:hover { text-decoration: underline; }
.address { color: var(--address-color); text-align: left; }
.bytes { color: var(--bytes-color); text-align: left; }
.mnemonic { color: var(--mnemonic-color); text-align: left; }
.operand { color: var(--operand-color); text-align: left; }
.comment { color: var(--comment-color); }
.label { color: var(--label-color); font-weight: bold; }
.mid-label { color: var(--mid-label-color); }
.separator-row { height: 15px; }
.code-cell { display: flex; align-items: top; padding: 0 !important; }
.code-cell .inline-label { width: 18ch; flex-shrink: 0; color: var(--label-color); font-weight: bold; }
.code-cell .mnemonic { min-width: 8ch; flex-shrink: 0; padding: 0 8px; }
.code-cell .operand { min-width: 32ch; flex-shrink: 0; padding: 0 8px; }
.code-cell .comment { padding: 0 8px; margin-left: 4ch; }
.code-cell.assignment { padding: 0 8px !important; }
.code-cell.assignment .label { min-width: 40ch; flex-shrink: 0; }
.code-cell.block-header .comment { margin-left: 0ch; }
#theme-toggle { position: fixed; top: 20px; right: 20px; padding: 8px 16px; background-color: var(--text-color); color: var(--bg-color); border: 1px solid var(--text-color); cursor: pointer; font-family: inherit; font-weight: bold; }
</style>
</head>
<body>
<button id="theme-toggle">Toggle Theme</button>
<table>
"#;

pub fn export_html(state: &AppState, path: &PathBuf) -> std::io::Result<()> {
    let formatter = state.get_formatter();
    let mut output = String::new();

    output.push_str(HTML_START);

    // Header block
    let source_name = state
        .file_path
        .as_ref()
        .and_then(|p| p.file_name())
        .and_then(|n| n.to_str())
        .unwrap_or("unknown");
    let separator =
        ";=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-";
    let version_line = format!(
        "; Auto-generated by Regenerator 2000 v{}",
        env!("CARGO_PKG_VERSION")
    );
    let header_lines = [
        separator,
        ";",
        &version_line,
        "; <a href=\"https://github.com/ricardoquesada/regenerator2000\">https://github.com/ricardoquesada/regenerator2000</a>",
        ";",
        &format!("; Exported from: {source_name}"),
        ";",
        separator,
    ];
    for header_line in &header_lines {
        output.push_str(&format!(
            "<tr><td colspan=\"5\" class=\"comment\">{}</td></tr>\n",
            header_line
        ));
    }
    output.push_str("<tr class=\"separator-row\"><td colspan=\"5\"></td></tr>\n");

    let ctx = crate::disassembler::DisassemblyContext {
        data: &state.raw_data,
        block_types: &state.block_types,
        labels: &state.labels,
        origin: state.origin,
        settings: &state.settings,
        system_comments: &state.system_comments,
        user_side_comments: &state.user_side_comments,
        user_line_comments: &state.user_line_comments,
        immediate_value_formats: &state.immediate_value_formats,
        cross_refs: &state.cross_refs,
        collapsed_blocks: &[], // Always uncollapse for export
        splitters: &state.splitters,
        scopes: &state.scopes,
    };
    let full_disassembly = state.disassembler.disassemble_ctx(&ctx);
    let external_lines = state.get_external_label_definitions(false);

    let mut label_name_to_addr = std::collections::HashMap::new();
    for (addr, label_vec) in &state.labels {
        for l in label_vec {
            label_name_to_addr.insert(l.name.clone(), *addr);
        }
    }

    let all_lines: Vec<&crate::disassembler::DisassemblyLine> = external_lines
        .iter()
        .chain(full_disassembly.iter())
        .collect();

    let mut formatted_rows = Vec::new();
    for line in &all_lines {
        let mut row_str = String::new();
        // Special case: Empty line (separator)
        if line.mnemonic.is_empty() && line.bytes.is_empty() && line.comment.is_empty() {
            row_str.push_str("<tr class=\"separator-row\"><td colspan=\"5\"></td></tr>\n");
            formatted_rows.push(row_str);
            continue;
        }

        // Special case: Splitter (internal only)
        if line.mnemonic == "{splitter}" {
            formatted_rows.push(row_str);
            continue;
        }

        // 1. Mid-instruction labels
        if line.bytes.len() > 1 {
            for j in 1..line.bytes.len() {
                let mid_addr = line.address.wrapping_add(j as u16);
                if let Some(label_vec) = state.labels.get(&mid_addr)
                    && let Some(label) =
                        crate::disassembler::resolve_label(label_vec, mid_addr.0, &state.settings)
                {
                    let mut name = label.name.clone();
                    if label.label_type == crate::state::LabelType::LocalUserDefined
                        && let Some(p) = formatter.local_label_prefix()
                        && !name.starts_with(p)
                    {
                        name = format!("{}{}", p, name);
                    }
                    let label_def = format!("{} =*+${:02x}", name, j);
                    row_str.push_str(&format!("<tr id=\"L{:04X}\"><td colspan=\"2\"></td><td colspan=\"3\" class=\"mid-label\">{}</td></tr>\n", mid_addr.0, label_def));
                }
            }
        }

        // 2. User line comments
        if let Some(comment) = &line.line_comment {
            for comment_line in comment.lines() {
                row_str.push_str(&format!(
                    "<tr><td colspan=\"2\"></td><td colspan=\"3\" class=\"code-cell block-header\"><span class=\"comment\">{}{}</span></td></tr>\n",
                    formatter.comment_prefix(),
                    comment_line
                ));
            }
        }

        // 3. Labels on top or inline
        let label_text = if let Some(label) = &line.label {
            formatter.format_label_definition(label)
        } else {
            String::new()
        };

        let mut inline_label_html = String::new();
        if !label_text.is_empty() {
            let label_on_own_line = label_text.len() > 18; // LABEL_COLUMN_WIDTH = 18
            if label_on_own_line {
                row_str.push_str(&format!("<tr><td colspan=\"2\"></td><td colspan=\"3\" class=\"label\" id=\"L{:04X}\">{}</td></tr>\n", line.address.0, label_text));
            } else {
                inline_label_html = format!(
                    "<span class=\"inline-label\" id=\"L{:04X}\">{}</span>",
                    line.address.0, label_text
                );
            }
        }

        if inline_label_html.is_empty() {
            inline_label_html = String::from("<span class=\"inline-label\"></span>");
        }

        // 4. Address part
        let address_td = if !line.bytes.is_empty() || line.label.is_some() {
            format!(
                "<td class=\"address\" id=\"L{:04X}\">${:04X}</td>",
                line.address.0, line.address.0
            )
        } else {
            "<td class=\"address\"></td>".to_string()
        };

        // 5. Bytes part
        let bytes_td = if line.show_bytes {
            let bytes_formatted = line
                .bytes
                .iter()
                .map(|b| format!("{:02x}", b))
                .collect::<Vec<_>>()
                .join(" ");
            format!("<td class=\"bytes\">{}</td>", bytes_formatted)
        } else {
            "<td class=\"bytes\"></td>".to_string()
        };

        // 6. Instruction part
        let mut operand_str = line.operand.clone();
        if let Some(target) = line.target_address {
            let origin_val = state.origin.0;
            let size = state.raw_data.len() as u16;
            if target.0 >= origin_val && target.0 < origin_val + size {
                operand_str = format!("<a href=\"#L{:04X}\">{}</a>", target.0, line.operand);
            }
        } else {
            let mut new_op = String::new();
            let mut current_word = String::new();
            for c in line.operand.chars() {
                if c.is_alphanumeric() || c == '_' {
                    current_word.push(c);
                } else {
                    if !current_word.is_empty() {
                        if let Some(addr) = label_name_to_addr.get(&current_word) {
                            new_op.push_str(&format!(
                                "<a href=\"#L{:04X}\">{}</a>",
                                addr.0, current_word
                            ));
                        } else {
                            new_op.push_str(&current_word);
                        }
                        current_word.clear();
                    }
                    new_op.push(c);
                }
            }
            if !current_word.is_empty() {
                if let Some(addr) = label_name_to_addr.get(&current_word) {
                    new_op.push_str(&format!(
                        "<a href=\"#L{:04X}\">{}</a>",
                        addr.0, current_word
                    ));
                } else {
                    new_op.push_str(&current_word);
                }
            }
            operand_str = new_op;
        }
        // 6. Instruction part
        let is_assignment = line.mnemonic.contains('=');

        // 7. Comment part
        let mut comment_str = line.comment.clone();
        // Format x-refs in comments as hyperlinks if they are internal
        if comment_str.contains("x-ref:") {
            let origin_val = state.origin.0;
            let size = state.raw_data.len() as u16;
            let words: Vec<String> = comment_str
                .split(' ')
                .map(|w| {
                    if w.starts_with('$') {
                        let hex_str = w.trim_matches(|c| c == '$' || c == ',' || c == ';');
                        if let Ok(addr) = u16::from_str_radix(hex_str, 16)
                            && addr >= origin_val
                            && addr < origin_val + size
                        {
                            return format!("<a href=\"#L{:04X}\">${:04X}</a>", addr, addr)
                                + if w.ends_with(',') { "," } else { "" };
                        }
                    }
                    w.to_string()
                })
                .collect();
            comment_str = words.join(" ");
        }

        let comment_part = if comment_str.is_empty() {
            String::new()
        } else {
            format!(
                "<span class=\"comment\">{} {}</span>",
                formatter.comment_prefix(),
                comment_str
            )
        };

        if is_assignment {
            let addr_val = line.external_label_address.unwrap_or(line.address).0;
            row_str.push_str(&format!(
                "<tr id=\"L{:04X}\"><td colspan=\"2\"></td><td colspan=\"3\" class=\"code-cell assignment\"><span class=\"label\">{} {}</span>{}</td></tr>\n",
                addr_val, line.mnemonic, operand_str, comment_part
            ));
        } else {
            row_str.push_str(&format!(
                "<tr>{}{}<td colspan=\"3\" class=\"code-cell\">{}<span class=\"mnemonic\">{}</span><span class=\"operand\">{}</span>{}</td></tr>\n",
                address_td, bytes_td, inline_label_html, line.mnemonic, operand_str, comment_part
            ));
        }
        formatted_rows.push(row_str);
    }
    let mut i = 0;
    while i < all_lines.len() {
        let line = all_lines[i];
        let offset = line.address.0 as isize - state.origin.0 as isize;
        let is_external = if offset >= 0 && (offset as usize) < state.block_types.len() {
            state.block_types[offset as usize] == crate::state::BlockType::ExternalFile
        } else {
            false
        };

        if is_external {
            let start_idx = i;
            let mut end_idx = i;
            while end_idx < all_lines.len() {
                let next_line = all_lines[end_idx];
                let next_offset = next_line.address.0 as isize - state.origin.0 as isize;
                let next_external = if next_offset >= 0
                    && (next_offset as usize) < state.block_types.len()
                {
                    state.block_types[next_offset as usize] == crate::state::BlockType::ExternalFile
                } else {
                    false
                };
                if !next_external {
                    break;
                }
                end_idx += 1;
            }

            let mut external_rows = String::new();
            for row in formatted_rows.iter().take(end_idx).skip(start_idx) {
                external_rows.push_str(row);
            }

            let base_name = path
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("export");
            let start_addr = all_lines[start_idx].address;
            let ext_filename = format!("{base_name}_{start_addr:04x}.html");
            let ext_path = path
                .parent()
                .unwrap_or(&std::path::PathBuf::from("."))
                .join(&ext_filename);

            let mut ext_output = String::new();
            ext_output.push_str(HTML_START);
            ext_output.push_str(&external_rows);
            ext_output.push_str(HTML_END);
            let _ = std::fs::write(&ext_path, ext_output);

            let link_row = format!(
                "<tr><td class=\"address\">${:04X}</td><td colspan=\"4\"><a href=\"{}\">Linked External Module: {}</a></td></tr>\n",
                start_addr.0, ext_filename, ext_filename
            );
            output.push_str(&link_row);

            i = end_idx;
        } else {
            output.push_str(&formatted_rows[i]);
            i += 1;
        }
    }

    const HTML_END: &str = r#"</table>
<script>
const toggleBtn = document.getElementById('theme-toggle');
const urlParams = new URLSearchParams(window.location.search);
let currentTheme = urlParams.get('theme') || 'dark';

function updateLinks() {
  document.querySelectorAll('a').forEach(link => {
    let href = link.getAttribute('href');
    if (href && !href.startsWith('#')) {
      let parts = href.split('?');
      let base = parts[0];
      let params = new URLSearchParams(parts[1] || '');
      params.set('theme', currentTheme);
      link.setAttribute('href', base + '?' + params.toString());
    }
  });
}

document.documentElement.setAttribute('data-theme', currentTheme);
toggleBtn.textContent = currentTheme === 'dark' ? 'Light Mode' : 'Dark Mode';
updateLinks();

toggleBtn.addEventListener('click', () => {
  currentTheme = currentTheme === 'dark' ? 'light' : 'dark';
  document.documentElement.setAttribute('data-theme', currentTheme);
  toggleBtn.textContent = currentTheme === 'dark' ? 'Light Mode' : 'Dark Mode';
  updateLinks();

  const newUrl = new URL(window.location.href);
  newUrl.searchParams.set('theme', currentTheme);
  window.history.pushState({}, '', newUrl);
});
</script>
</body>
</html>
"#;

    output.push_str(HTML_END);
    std::fs::write(path, output)
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_export_html() {
        let mut state = AppState::new();
        state.origin = crate::state::Addr(0x1000);
        state.raw_data = vec![0xA9, 0x00, 0x8D, 0x20, 0xD0, 0x60];
        state.block_types = vec![crate::state::BlockType::Code; 6];

        state.labels.insert(
            crate::state::Addr(0x1000),
            vec![crate::state::Label {
                name: "Start".to_string(),
                kind: crate::state::LabelKind::User,
                label_type: crate::state::LabelType::UserDefined,
            }],
        );

        let path = PathBuf::from("test_output.html");
        let _ = std::fs::remove_file(&path);

        let res = export_html(&state, &path);
        assert!(res.is_ok());

        let content = std::fs::read_to_string(&path).unwrap();

        assert!(content.contains("<!DOCTYPE html>"));
        assert!(content.contains("<table>"));
        assert!(content.contains("</table>"));

        assert!(content.contains("id=\"L1000\""));
        assert!(content.contains("id=\"L1002\""));

        assert!(content.contains("a9 00"));
        assert!(content.contains("8d 20 d0"));

        assert!(content.contains("class=\"mnemonic\""));
        assert!(content.contains("class=\"operand\""));

        let _ = std::fs::remove_file(&path);
    }
}
